//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOPS.WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SOPS.WebUI.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coś poszło nie tak spróbuj jeszcze raz..
        /// </summary>
        internal static string AccountController_Login_SomethingGoesWrong {
            get {
                return ResourceManager.GetString("AccountController_Login_SomethingGoesWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana nazwa użytkownika bądź hasło są nieprawidłowe.
        /// </summary>
        internal static string AccountController_Login_UserNotExist {
            get {
                return ResourceManager.GetString("AccountController_Login_UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bieżące hasło.
        /// </summary>
        internal static string ChangePasswordViewModel_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        internal static string ChangePasswordViewModel_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź.
        /// </summary>
        internal static string ChangePasswordViewModel_PasswordAnswer {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_PasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz odpowiedź.
        /// </summary>
        internal static string ChangePasswordViewModel_PasswordAnswerConfirm {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_PasswordAnswerConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        internal static string ChangePasswordViewModel_PasswordConfirm {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie.
        /// </summary>
        internal static string ChangePasswordViewModel_PasswordQuestion {
            get {
                return ResourceManager.GetString("ChangePasswordViewModel_PasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        internal static string CompanyViewModel_City {
            get {
                return ResourceManager.GetString("CompanyViewModel_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string CompanyViewModel_Description {
            get {
                return ResourceManager.GetString("CompanyViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CompanyViewModel_Email {
            get {
                return ResourceManager.GetString("CompanyViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa firmy.
        /// </summary>
        internal static string CompanyViewModel_Name {
            get {
                return ResourceManager.GetString("CompanyViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string CompanyViewModel_Phone {
            get {
                return ResourceManager.GetString("CompanyViewModel_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        internal static string CompanyViewModel_PostalCode {
            get {
                return ResourceManager.GetString("CompanyViewModel_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        internal static string CompanyViewModel_Street {
            get {
                return ResourceManager.GetString("CompanyViewModel_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres www.
        /// </summary>
        internal static string CompanyViewModel_Url {
            get {
                return ResourceManager.GetString("CompanyViewModel_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadzone wartości są od siebie różne.
        /// </summary>
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        internal static string ContractViewModel_City {
            get {
                return ResourceManager.GetString("ContractViewModel_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        internal static string ContractViewModel_CompanyId {
            get {
                return ResourceManager.GetString("ContractViewModel_CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opiektun ze strony firmy.
        /// </summary>
        internal static string ContractViewModel_CompanyRepresentative {
            get {
                return ResourceManager.GetString("ContractViewModel_CompanyRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zakończenia praktyk.
        /// </summary>
        internal static string ContractViewModel_EndDate {
            get {
                return ResourceManager.GetString("ContractViewModel_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        internal static string ContractViewModel_PostalCode {
            get {
                return ResourceManager.GetString("ContractViewModel_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rozpoczęcia praktyk.
        /// </summary>
        internal static string ContractViewModel_StartDate {
            get {
                return ResourceManager.GetString("ContractViewModel_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        internal static string ContractViewModel_Street {
            get {
                return ResourceManager.GetString("ContractViewModel_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opiekun ze strony uczelni.
        /// </summary>
        internal static string ContractViewModel_UniversityRepresentative {
            get {
                return ResourceManager.GetString("ContractViewModel_UniversityRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opiekun.
        /// </summary>
        internal static string CourseViewModel_Keeper {
            get {
                return ResourceManager.GetString("CourseViewModel_Keeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa kierunku.
        /// </summary>
        internal static string CourseViewModel_Name {
            get {
                return ResourceManager.GetString("CourseViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szablon umowy.
        /// </summary>
        internal static string CourseViewModel_Template {
            get {
                return ResourceManager.GetString("CourseViewModel_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string CreateEmployeeViewModel_Administrator {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź.
        /// </summary>
        internal static string CreateEmployeeViewModel_Answer {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz odpowiedź.
        /// </summary>
        internal static string CreateEmployeeViewModel_AnswerConfirm {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_AnswerConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierunek.
        /// </summary>
        internal static string CreateEmployeeViewModel_Course {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydział.
        /// </summary>
        internal static string CreateEmployeeViewModel_Department {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CreateEmployeeViewModel_Email {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        internal static string CreateEmployeeViewModel_FirstName {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opiekun.
        /// </summary>
        internal static string CreateEmployeeViewModel_Keeper {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_Keeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string CreateEmployeeViewModel_LastName {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokowany.
        /// </summary>
        internal static string CreateEmployeeViewModel_LockedOut {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        internal static string CreateEmployeeViewModel_Moderator {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string CreateEmployeeViewModel_Password {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie hasła.
        /// </summary>
        internal static string CreateEmployeeViewModel_PasswordConfirm {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie.
        /// </summary>
        internal static string CreateEmployeeViewModel_Question {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super administrator.
        /// </summary>
        internal static string CreateEmployeeViewModel_SuperAdministrator {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_SuperAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        internal static string CreateEmployeeViewModel_UserName {
            get {
                return ResourceManager.GetString("CreateEmployeeViewModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa wydziału.
        /// </summary>
        internal static string DepartmentViewModel_Name {
            get {
                return ResourceManager.GetString("DepartmentViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string EmployeeViewModel_Administrator {
            get {
                return ResourceManager.GetString("EmployeeViewModel_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierunek.
        /// </summary>
        internal static string EmployeeViewModel_Course {
            get {
                return ResourceManager.GetString("EmployeeViewModel_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydział.
        /// </summary>
        internal static string EmployeeViewModel_Department {
            get {
                return ResourceManager.GetString("EmployeeViewModel_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmployeeViewModel_Email {
            get {
                return ResourceManager.GetString("EmployeeViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        internal static string EmployeeViewModel_FirstName {
            get {
                return ResourceManager.GetString("EmployeeViewModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opiekun.
        /// </summary>
        internal static string EmployeeViewModel_Keeper {
            get {
                return ResourceManager.GetString("EmployeeViewModel_Keeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string EmployeeViewModel_LastName {
            get {
                return ResourceManager.GetString("EmployeeViewModel_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokowany.
        /// </summary>
        internal static string EmployeeViewModel_LockedOut {
            get {
                return ResourceManager.GetString("EmployeeViewModel_LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        internal static string EmployeeViewModel_Moderator {
            get {
                return ResourceManager.GetString("EmployeeViewModel_Moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rola.
        /// </summary>
        internal static string EmployeeViewModel_Role {
            get {
                return ResourceManager.GetString("EmployeeViewModel_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super administrator.
        /// </summary>
        internal static string EmployeeViewModel_SuperAdministrator {
            get {
                return ResourceManager.GetString("EmployeeViewModel_SuperAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string LoginViewModel_Password {
            get {
                return ResourceManager.GetString("LoginViewModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapamiętaj mnie.
        /// </summary>
        internal static string LoginViewModel_Remember {
            get {
                return ResourceManager.GetString("LoginViewModel_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        internal static string LoginViewModel_UserName {
            get {
                return ResourceManager.GetString("LoginViewModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalna ilość znaków {1}.
        /// </summary>
        internal static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdzono.
        /// </summary>
        internal static string OfferViewModel_Approved {
            get {
                return ResourceManager.GetString("OfferViewModel_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa firmy.
        /// </summary>
        internal static string OfferViewModel_Company {
            get {
                return ResourceManager.GetString("OfferViewModel_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data dodania.
        /// </summary>
        internal static string OfferViewModel_Date {
            get {
                return ResourceManager.GetString("OfferViewModel_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string OfferViewModel_Description {
            get {
                return ResourceManager.GetString("OfferViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł oferty.
        /// </summary>
        internal static string OfferViewModel_Title {
            get {
                return ResourceManager.GetString("OfferViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branża.
        /// </summary>
        internal static string OfferViewModel_Trade {
            get {
                return ResourceManager.GetString("OfferViewModel_Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj oferty.
        /// </summary>
        internal static string OfferViewModel_Type {
            get {
                return ResourceManager.GetString("OfferViewModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegisterViewModel_Email {
            get {
                return ResourceManager.GetString("RegisterViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        internal static string RegisterViewModel_FirstName {
            get {
                return ResourceManager.GetString("RegisterViewModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string RegisterViewModel_LastName {
            get {
                return ResourceManager.GetString("RegisterViewModel_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        internal static string RegisterViewModel_Password {
            get {
                return ResourceManager.GetString("RegisterViewModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź.
        /// </summary>
        internal static string RegisterViewModel_PasswordAnswer {
            get {
                return ResourceManager.GetString("RegisterViewModel_PasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz odpowiedź.
        /// </summary>
        internal static string RegisterViewModel_PasswordAnswerConfirm {
            get {
                return ResourceManager.GetString("RegisterViewModel_PasswordAnswerConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz hasło.
        /// </summary>
        internal static string RegisterViewModel_PasswordConfirm {
            get {
                return ResourceManager.GetString("RegisterViewModel_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie pomocnicze.
        /// </summary>
        internal static string RegisterViewModel_PasswordQuestion {
            get {
                return ResourceManager.GetString("RegisterViewModel_PasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        internal static string RegisterViewModel_UserName {
            get {
                return ResourceManager.GetString("RegisterViewModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole {0} jest wymagane.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź.
        /// </summary>
        internal static string ResetPasswordViewModel_PasswordAnswer {
            get {
                return ResourceManager.GetString("ResetPasswordViewModel_PasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer albumu.
        /// </summary>
        internal static string StudentViewModel_Album {
            get {
                return ResourceManager.GetString("StudentViewModel_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        internal static string StudentViewModel_City {
            get {
                return ResourceManager.GetString("StudentViewModel_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kierunek.
        /// </summary>
        internal static string StudentViewModel_Course {
            get {
                return ResourceManager.GetString("StudentViewModel_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydział.
        /// </summary>
        internal static string StudentViewModel_Department {
            get {
                return ResourceManager.GetString("StudentViewModel_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string StudentViewModel_Email {
            get {
                return ResourceManager.GetString("StudentViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string StudentViewModel_LastName {
            get {
                return ResourceManager.GetString("StudentViewModel_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryb studiów.
        /// </summary>
        internal static string StudentViewModel_Mode {
            get {
                return ResourceManager.GetString("StudentViewModel_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        internal static string StudentViewModel_Name {
            get {
                return ResourceManager.GetString("StudentViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string StudentViewModel_Phone {
            get {
                return ResourceManager.GetString("StudentViewModel_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        internal static string StudentViewModel_PostalCode {
            get {
                return ResourceManager.GetString("StudentViewModel_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specjalizacja.
        /// </summary>
        internal static string StudentViewModel_Specialization {
            get {
                return ResourceManager.GetString("StudentViewModel_Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        internal static string StudentViewModel_Street {
            get {
                return ResourceManager.GetString("StudentViewModel_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres uczelni.
        /// </summary>
        internal static string UniversityViewModel_Address {
            get {
                return ResourceManager.GetString("UniversityViewModel_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa uczelni.
        /// </summary>
        internal static string UniversityViewModel_Name {
            get {
                return ResourceManager.GetString("UniversityViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UpdateProfileViewModel_Email {
            get {
                return ResourceManager.GetString("UpdateProfileViewModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokowany.
        /// </summary>
        internal static string UpdateProfileViewModel_IsLockedOut {
            get {
                return ResourceManager.GetString("UpdateProfileViewModel_IsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        internal static string UpdateProfileViewModel_LastName {
            get {
                return ResourceManager.GetString("UpdateProfileViewModel_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        internal static string UpdateProfileViewModel_UserName {
            get {
                return ResourceManager.GetString("UpdateProfileViewModel_UserName", resourceCulture);
            }
        }
    }
}
